[versions]

# kotlin
kotlin = "1.9.0"
kotlinx-coroutines = "1.7.3"

# compose
jetbrains-compose = "1.5.0"
androidx-compose = "1.5.0"
androidx-compose-compiler = "1.5.0"
androidx-compose-material3 = "1.1.2"

# android
android-plugin = "8.1.2"
androidx-annotation = "1.6.0"
androidx-core = "1.10.1"
androidx-exifinterface = "1.3.6"
androidx-lifecycle = "2.6.1"
androidx-multidex = "2.0.1"
androidx-navigation = "2.7.0"
androidx-paging = "3.2.1"
androidx-swiperefreshlayout = "1.1.0"
androidx-test-ext-junit = "1.1.5"
androidx-test-runner = "1.5.2"
androidx-test-rules = "1.5.0"
androidx-appcompat = "1.6.1"
androidx-constraintlayout-compose = "1.0.1"

# google
google-accompanist = "0.30.1"
google-material = "1.9.0"

# panpf
panpf-assemblyadapter4 = "4.1.0"
panpf-sketch3 = "3.2.5"
panpf-tools4a = "1.0.0"
panpf-tools4j = "1.0.0"
panpf-tools4k = "1.0.0"

# other
junit = "4.13.2"
telephoto = "0.6.2"
mmkv = "1.2.13"
subsamplingscaleimageview = "3.10.0"
photoview = "2.3.0"
coil = "2.4.0"
glide = "4.15.1"
glide-ktx = "1.0.0-beta01"
picasso = "2.8"
mavenpublish = "0.25.3"

[libraries]

# kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }

# compose
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "androidx-compose" }

# android
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "androidx-multidex" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout-compose" }

# google
google-drawablepainer = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "google-accompanist" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }

# panpf
panpf-assemblyadapter4 = { module = "io.github.panpf.assemblyadapter4:assemblyadapter", version.ref = "panpf-assemblyadapter4" }
panpf-sketch3 = { module = "io.github.panpf.sketch3:sketch", version.ref = "panpf-sketch3" }
panpf-sketch3-compose = { module = "io.github.panpf.sketch3:sketch-compose", version.ref = "panpf-sketch3" }
panpf-sketch3-extensions = { module = "io.github.panpf.sketch3:sketch-extensions", version.ref = "panpf-sketch3" }
panpf-sketch3-viewability = { module = "io.github.panpf.sketch3:sketch-viewability", version.ref = "panpf-sketch3" }
panpf-tools4j = { module = "io.github.panpf.tools4j:tools4j-ktx", version.ref = "panpf-tools4j" }
panpf-tools4j-test = { module = "io.github.panpf.tools4j:tools4j-test-ktx", version.ref = "panpf-tools4j" }
panpf-tools4a = { module = "io.github.panpf.tools4a:tools4a-ktx", version.ref = "panpf-tools4a" }
panpf-tools4k = { module = "io.github.panpf.tools4k:tools4k", version.ref = "panpf-tools4k" }

# other
junit = { module = "junit:junit", version.ref = "junit" }
telephoto = { module = "me.saket.telephoto:zoomable-image-coil", version.ref = "telephoto" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
subsamplingscaleimageview = { module = "com.davemorrissey.labs:subsampling-scale-image-view-androidx", version.ref = "subsamplingscaleimageview" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ktx = { module = "com.github.bumptech.glide:ktx", version.ref = "glide-ktx" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-plugin" }
com-android-library = { id = "com.android.library", version.ref = "android-plugin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
org-jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
org-jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
mavenpublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenpublish" }

[bundles]

