[versions]
android-plugin = "8.7.1"
androidx-activity = "1.9.0"
androidx-appcompat = "1.7.0"
androidx-compose = "1.7.1" # sync with jetbrains-compose
androidx-constraintlayout = "2.1.4"
androidx-constraintlayout-compose = "1.0.1"
androidx-datastore = "1.1.1"
androidx-exifinterface = "1.3.7"
androidx-lifecycle = "2.8.5" # sync with jetbrains-lifecycle
androidx-navigation = "2.8.0"
androidx-recyclerview = "1.3.2"
androidx-swiperefreshlayout = "1.1.0"
androidx-test-ext-junit = "1.2.1"
androidx-test-rules = "1.6.1"
androidx-test-runner = "1.6.2"
androidx-vectordrawable = "1.2.0"

buildkonfig = "0.15.2"

appdirs = "1.2.2"

cashapp-paging = "3.3.0-alpha02-0.5.1"

coil3 = "3.0.4"
coil2 = "2.7.0"

glide = "4.15.1"
glide-ktx = "1.0.0-beta01"
google-accompanist = "0.36.0"
google-material = "1.12.0"

jetbrains-compose = "1.7.0"
jetbrains-lifecycle = "2.8.3"

kotlin = "2.0.21"
kotlinx-atomicfu = "0.26.0" # sync with kotlin
kotlinx-collections-immutable = "0.3.8"
kotlinx-coroutines = "1.9.0"
kotlinx-cover = "0.8.3"
kotlinx-serialization-json = "1.7.3"
ktor = "3.0.0"

leakcanary = "2.14"

mavenpublish = "0.29.0"
moko-permissions = "0.18.0"

okio = "3.9.1"

panpf-assemblyadapter4 = "4.1.0"
panpf-sketch3 = "3.3.2"
panpf-sketch4 = "4.0.0"
panpf-tools4a = "1.0.0"
panpf-tools4j = "1.0.0"
panpf-tools4k = "1.0.0"

picasso = "2.8"
photoview = "2.3.0"

skiko = "0.8.15"    # sync with jetbrains-compose
subsamplingscaleimageview = "3.10.0"

voyager = "1.1.0-alpha03"

[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
gradlePlugin-androidxNavigationSafeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
gradlePlugin-buildkonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfig" }
gradlePlugin-jetbrainsCompose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrains-compose" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-kotlinComposeCompiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-kotlinSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
gradlePlugin-kotlinxAtomicfu = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "kotlinx-atomicfu" }
gradlePlugin-kotlinxCover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kotlinx-cover" }
gradlePlugin-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenpublish" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-ui-test-junit4-android = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "androidx-compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout-compose" }
androidx-datastore-core-okio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "androidx-datastore" }
androidx-datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-vectordrawable-animated = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "androidx-vectordrawable" }

appdirs = { module = "net.harawata:appdirs", version.ref = "appdirs" }

cashapp-paging-compose-common = { module = "app.cash.paging:paging-compose-common", version.ref = "cashapp-paging" }

coil2 = { module = "io.coil-kt:coil", version.ref = "coil2" }
coil2-base = { module = "io.coil-kt:coil-base", version.ref = "coil2" }
coil2-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil2" }
coil2-compose-base = { module = "io.coil-kt:coil-compose-base", version.ref = "coil2" }

coil3 = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
coil3-core = { module = "io.coil-kt.coil3:coil-core", version.ref = "coil3" }
coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil3-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coil3-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil3" }

google-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "google-accompanist" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ktx = { module = "com.github.bumptech.glide:ktx", version.ref = "glide-ktx" }

jetbrains-lifecycle-common = { module = "org.jetbrains.androidx.lifecycle:lifecycle-common", version.ref = "jetbrains-lifecycle" }
jetbrains-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrains-lifecycle" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-serialization-kotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

moko-permissions = { module = "dev.icerock.moko:permissions-compose", version.ref = "moko-permissions" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

panpf-assemblyadapter4-pager2 = { module = "io.github.panpf.assemblyadapter4:assemblyadapter-pager2", version.ref = "panpf-assemblyadapter4" }
panpf-assemblyadapter4-recycler = { module = "io.github.panpf.assemblyadapter4:assemblyadapter-recycler", version.ref = "panpf-assemblyadapter4" }
panpf-assemblyadapter4-recycler-paging = { module = "io.github.panpf.assemblyadapter4:assemblyadapter-recycler-paging", version.ref = "panpf-assemblyadapter4" }

panpf-sketch3 = { module = "io.github.panpf.sketch3:sketch", version.ref = "panpf-sketch3" }
panpf-sketch3-compose = { module = "io.github.panpf.sketch3:sketch-compose", version.ref = "panpf-sketch3" }
panpf-sketch3-core = { module = "io.github.panpf.sketch3:sketch-core", version.ref = "panpf-sketch3" }
panpf-sketch3-compose-core = { module = "io.github.panpf.sketch3:sketch-compose-core", version.ref = "panpf-sketch3" }
panpf-sketch3-viewability = { module = "io.github.panpf.sketch3:sketch-viewability", version.ref = "panpf-sketch3" }

panpf-sketch4-animated-gif = { module = "io.github.panpf.sketch4:sketch-animated-gif", version.ref = "panpf-sketch4" }
panpf-sketch4-core = { module = "io.github.panpf.sketch4:sketch-core", version.ref = "panpf-sketch4" }
panpf-sketch4-compose = { module = "io.github.panpf.sketch4:sketch-compose", version.ref = "panpf-sketch4" }
panpf-sketch4-compose-core = { module = "io.github.panpf.sketch4:sketch-compose-core", version.ref = "panpf-sketch4" }
panpf-sketch4-compose-resources = { module = "io.github.panpf.sketch4:sketch-compose-resources", version.ref = "panpf-sketch4" }
panpf-sketch4-extensions-compose = { module = "io.github.panpf.sketch4:sketch-extensions-compose", version.ref = "panpf-sketch4" }
panpf-sketch4-extensions-view = { module = "io.github.panpf.sketch4:sketch-extensions-view", version.ref = "panpf-sketch4" }
panpf-sketch4-extensions-viewability = { module = "io.github.panpf.sketch4:sketch-extensions-viewability", version.ref = "panpf-sketch4" }
panpf-sketch4-http-ktor3 = { module = "io.github.panpf.sketch4:sketch-http-ktor3", version.ref = "panpf-sketch4" }
panpf-sketch4-svg = { module = "io.github.panpf.sketch4:sketch-svg", version.ref = "panpf-sketch4" }
panpf-sketch4-singleton = { module = "io.github.panpf.sketch4:sketch-singleton", version.ref = "panpf-sketch4" }
panpf-sketch4-view = { module = "io.github.panpf.sketch4:sketch-view", version.ref = "panpf-sketch4" }
panpf-sketch4-view-core = { module = "io.github.panpf.sketch4:sketch-view-core", version.ref = "panpf-sketch4" }

panpf-tools4a-activity = { module = "io.github.panpf.tools4a:tools4a-activity-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-device = { module = "io.github.panpf.tools4a:tools4a-device-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-dimen = { module = "io.github.panpf.tools4a:tools4a-dimen-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-display = { module = "io.github.panpf.tools4a:tools4a-display-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-fileprovider = { module = "io.github.panpf.tools4a:tools4a-fileprovider-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-network = { module = "io.github.panpf.tools4a:tools4a-network-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-run = { module = "io.github.panpf.tools4a:tools4a-run-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-test = { module = "io.github.panpf.tools4a:tools4a-test-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-toast = { module = "io.github.panpf.tools4a:tools4a-toast-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-view = { module = "io.github.panpf.tools4a:tools4a-view-ktx", version.ref = "panpf-tools4a" }

panpf-tools4j-reflect = { module = "io.github.panpf.tools4j:tools4j-reflect-ktx", version.ref = "panpf-tools4j" }

panpf-tools4k = { module = "io.github.panpf.tools4k:tools4k", version.ref = "panpf-tools4k" }

photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }

skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }
subsamplingscaleimageview = { module = "com.davemorrissey.labs:subsampling-scale-image-view-androidx", version.ref = "subsamplingscaleimageview" }

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
#voyager-bottomSheetNavigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
#voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
#voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
#voyager-hilt = { module = "cafe.adriel.voyager:voyager-hilt", version.ref = "voyager" }
#voyager-kodein = { module = "cafe.adriel.voyager:voyager-kodein", version.ref = "voyager" }
#voyager-rxjava = { module = "cafe.adriel.voyager:voyager-rxjava", version.ref = "voyager" }